CREATE TABLE IF NOT EXISTS users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIVILEGES TINYINT DEFAULT 0,
    TIME_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);